### ISSUE TITLE
Update mustache/mustache

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/wp-posts-to-posts#3]
- https://packagist.org/packages/mustache/mustache
- https://github.com/bobthecow/mustache.php

**Comment by versusbassz** [comment]
The Fatal error in the old version:
```text
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ValueError: Unknown format specifier "i" in /var/www/html/wp-content/plugins/wp-posts-to-posts/vendor/mustache/mustache/src/Mustache/Engine.php:606
my_wordpress_project_nginx | Stack trace:
my_wordpress_project_nginx | #0 /var/www/html/wp-content/plugins/wp-posts-to-posts/vendor/mustache/mustache/src/Mustache/Engine.php(606): sprintf()
my_wordpress_project_nginx | #1 /var/www/html/wp-content/plugins/wp-posts-to-posts/vendor/mustache/mustache/src/Mustache/Engine.php(691): Mustache_Engine->getTemplateClassName()
my_wordpress_project_nginx | #2 /var/www/html/wp-content/plugins/wp-posts-to-posts/vendor/mustache/mustache/src/Mustache/Engine.php(619): Mustache_Engine->loadSource()
my_wordpress_project_nginx | #3 /var/www/html/wp-content/plugins/wp-posts-to-posts/vendor/mustache/mustache/src/Mustache/Engine.php(219): Mustache_Engine->loadTemplate()
my_wordpress_project_nginx | #4 /var/www/html/wp-content/plugins/wp-posts-to-posts/admin/mustache.php(21): Mustache_Engine->render()
my_wordpress_project_nginx | #5 /var/www/html/wp-content/plugins/wp-posts-to-posts/admin/field-delete.php(10): P2P_Mustache::render()
my_wordpress_project_nginx | #6 /var/www/html/wp-content/plugins/wp-posts-to-posts/admin/box.php(116): P2P_Field_Delete->get_title()
my_wordpress_project_nginx | #7 /var/www/html/wp-content/plugins/wp-posts-to-posts/admin/box.php(78): P2P_Box->render_connections_table()
my_wordpress_project_nginx | #8 /var/www/html/wp-admin/includes/template.php(1395): P2P_Box->render()
my_wordpress_project_nginx | #9 /var/www/html/wp-admin/includes/post.php(2296): do_meta_boxes()
my_wordpress_project_nginx | #10 /var/www/html/wp-admin/edit-form-blocks.php(309): the_block_editor_meta_boxes()
my_wordpress_project_nginx | #11 /var/www/html/wp-admin/post.php(187): require('...')
my_wordpress_project_nginx | #12 {main}
my_wordpress_project_nginx |   thrown in /var/www/html/wp-content/plugins/wp-posts-to-posts/vendor/mustache/mustache/src/Mustache/Engine.php on line 606" while reading upstream, client: 172.21.0.3, server: default, request: "GET /wp-admin/post.php?post=1&action=edit HTTP/1.1
```
